language: node_js
node_js:
  - 8
  - 10
  - 12

env:
  - SEQUELIZE_VERSION="^5.21.6"

before_install:
  - yarn add sequelize@$SEQUELIZE_VERSION

script:
  - yarn test

services:
  - redis-server
  - memcached